import type { Building, Destination, IndoorNode, NavigationEdge, Person, QRLocation } from "./wayfindr-types";

export const DEMO_BUILDING: Building = {
  id: "building-a",
  name: "Building A",
  floors: [
    { id: "floor-g", name: "Ground Floor", level: "G" },
    { id: "floor-1", name: "First Floor", level: "1" },
    { id: "floor-2", name: "Second Floor", level: "2" },
  ],
};

export const DEMO_NODES: IndoorNode[] = [
  // Ground Floor Nodes
  { id: "node-main-gate", floorId: "G", x: 20, y: 88, name: "Main Gate Entrance", type: "entrance" },
  { id: "node-reception", floorId: "G", x: 20, y: 65, name: "Reception Lobby", type: "corridor" },
  { id: "node-central-corridor", floorId: "G", x: 45, y: 65, name: "Central Corridor", type: "corridor" },
  { id: "node-[#1st-bedroom]", floorId: "G", x: 75, y: 85, name: "1st Bedroom", type: "room" },
  { id: "node-dining-room", floorId: "G", x: 80, y: 65, name: "Dining Room", type: "room" },
  { id: "node-kitchen", floorId: "G", x: 75, y: 35, name: "Kitchen", type: "room" },
  { id: "node-porch", floorId: "G", x: 75, y: 15, name: "Porch", type: "room" },
  { id: "node-bathroom", floorId: "G", x: 25, y: 38, name: "Bathroom", type: "restroom" },
  { id: "node-2nd-bedroom", floorId: "G", x: 40, y: 28, name: "2nd Bedroom", type: "room" },
  { id: "node-bhagwan-room", floorId: "G", x: 30, y: 15, name: "Bhagwan Room", type: "room" },
  { id: "node-admissions", floorId: "G", x: 50, y: 85, name: "Admissions Office", type: "room" },
  { id: "node-library", floorId: "G", x: 50, y: 38, name: "Library", type: "room" },
  { id: "node-stairs-g", floorId: "G", x: 60, y: 65, name: "Ground Staircase", type: "staircase" },
  { id: "node-elevator-g", floorId: "G", x: 35, y: 65, name: "Elevator Block", type: "elevator" },

  // First Floor Nodes
  { id: "node-stairs-1", floorId: "1", x: 60, y: 65, name: "Floor 1 Staircase", type: "staircase" },
  { id: "node-elevator-1", floorId: "1", x: 35, y: 65, name: "Floor 1 Elevator", type: "elevator" },
  { id: "node-faculty-cabins", floorId: "1", x: 75, y: 40, name: "Faculty Cabins Block", type: "room" },
  { id: "node-faculty-room-201", floorId: "1", x: 25, y: 40, name: "Faculty Room 201", type: "room" },

  // Second Floor Nodes
  { id: "node-stairs-2", floorId: "2", x: 60, y: 65, name: "Floor 2 Staircase", type: "staircase" },
  { id: "node-elevator-2", floorId: "2", x: 35, y: 65, name: "Floor 2 Elevator", type: "elevator" },
  { id: "node-director-office", floorId: "2", x: 50, y: 30, name: "Director Office", type: "room" },
];

export const DEMO_DESTINATIONS: Destination[] = [
  {
    id: "admissions",
    name: "Admissions Office",
    category: "Admissions",
    nodeId: "node-admissions",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "GraduationCap",
    description: "Student counseling, fee payment, and admission queries.",
    hours: "9:00 AM - 5:00 PM",
    roomNumber: "Room G-04",
  },
  {
    id: "library",
    name: "Library",
    category: "Library",
    nodeId: "node-library",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "Library",
    description: "Central study hall, reference books, digital catalog.",
    hours: "8:00 AM - 9:00 PM",
    roomNumber: "Room G-10",
  },
  {
    id: "faculty-cabins",
    name: "Faculty Cabins",
    category: "Faculty",
    nodeId: "node-faculty-cabins",
    floorId: "1",
    buildingName: "Building A",
    floorName: "First Floor",
    icon: "UserRoundCheck",
    description: "Professors & department faculty meeting rooms.",
    hours: "10:00 AM - 4:00 PM",
    roomNumber: "Floor 1 Block B",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    category: "Kitchen",
    nodeId: "node-kitchen",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "Utensils",
    description: "Food preparation & water refreshment area.",
    hours: "Open 24/7",
    roomNumber: "Kitchen G-02",
  },
  {
    id: "first-bedroom",
    name: "1st Bedroom",
    category: "Bedrooms",
    nodeId: "node-[#1st-bedroom]",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "Bed",
    description: "Lower-right bedroom room.",
    hours: "Private Access",
    roomNumber: "Room 101",
  },
  {
    id: "second-bedroom",
    name: "2nd Bedroom",
    category: "Bedrooms",
    nodeId: "node-2nd-bedroom",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "BedDouble",
    description: "Upper-left bedroom room.",
    hours: "Private Access",
    roomNumber: "Room 102",
  },
  {
    id: "bhagwan-room",
    name: "Bhagwan Room",
    category: "Prayer",
    nodeId: "node-bhagwan-room",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "Flame",
    description: "Peaceful prayer & meditation room.",
    hours: "Open 24/7",
    roomNumber: "Prayer Sanctuary",
  },
  {
    id: "bathroom",
    name: "Restroom / Bathroom",
    category: "Restroom",
    nodeId: "node-bathroom",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "Droplets",
    description: "Clean accessible washroom & freshen up area.",
    hours: "Open 24/7",
    roomNumber: "Restroom G-01",
  },
  {
    id: "dining-room",
    name: "Dining Room",
    category: "Kitchen",
    nodeId: "node-dining-room",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "Coffee",
    description: "Dining area connected to Kitchen & Central Hall.",
    hours: "Open 24/7",
    roomNumber: "Dining Hall",
  },
  {
    id: "porch",
    name: "Porch",
    category: "Facility",
    nodeId: "node-porch",
    floorId: "G",
    buildingName: "Building A",
    floorName: "Ground Floor",
    icon: "Sun",
    description: "Open outdoor porch sitting area.",
    hours: "Open 24/7",
    roomNumber: "Outdoor Porch",
  },
];

export const DEMO_PEOPLE: Person[] = [
  {
    id: "person-tarun",
    name: "Tarun Kumar",
    title: "Teaching Faculty",
    department: "Computer Science",
    destinationId: "faculty-cabins",
    nodeId: "node-faculty-room-201",
    roomNumber: "Cabin 201",
    floorName: "First Floor",
    buildingName: "Building A",
  },
  {
    id: "person-tanya",
    name: "Tanya Sharma",
    title: "Admissions Counselor",
    department: "Student Admissions",
    destinationId: "admissions",
    nodeId: "node-admissions",
    roomNumber: "Room G-04",
    floorName: "Ground Floor",
    buildingName: "Building A",
  },
  {
    id: "person-[#rahul]",
    name: "Rahul Verma",
    title: "Chief Administrator",
    department: "Reception Desk",
    destinationId: "reception",
    nodeId: "node-reception",
    roomNumber: "Desk 102",
    floorName: "Ground Floor",
    buildingName: "Building A",
  },
  {
    id: "person-[#ananya]",
    name: "Dr. Ananya Roy",
    title: "Campus Director",
    department: "Directorate",
    destinationId: "director-office",
    nodeId: "node-director-office",
    roomNumber: "Suite 301",
    floorName: "Second Floor",
    buildingName: "Building A",
  },
  {
    id: "person-priya",
    name: "Priya Patel",
    title: "Head Librarian",
    department: "Library & Information Services",
    destinationId: "library",
    nodeId: "node-library",
    roomNumber: "Room G-10",
    floorName: "Ground Floor",
    buildingName: "Building A",
  },
  {
    id: "person-[#amit]",
    name: "Amit Shah",
    title: "Kitchen Supervisor",
    department: "Dining & Refreshments",
    destinationId: "kitchen",
    nodeId: "node-kitchen",
    roomNumber: "Kitchen G-02",
    floorName: "Ground Floor",
    buildingName: "Building A",
  },
];

export const DEMO_QR_LOCATIONS: Record<string, QRLocation> = {
  "main-gate": {
    qrId: "main-gate",
    nodeId: "node-main-gate",
    locationName: "Main Gate Entrance",
    buildingName: "Building A",
    floorName: "Ground Floor",
    floorId: "G",
  },
  reception: {
    qrId: "reception",
    nodeId: "node-reception",
    locationName: "Reception Lobby",
    buildingName: "Building A",
    floorName: "Ground Floor",
    floorId: "G",
  },
  "floor-1": {
    qrId: "floor-1",
    nodeId: "node-stairs-1",
    locationName: "Floor 1 Landing",
    buildingName: "Building A",
    floorName: "First Floor",
    floorId: "1",
  },
};

export const DEMO_EDGES: NavigationEdge[] = [
  // Ground Floor Edges
  { from: "node-main-gate", to: "node-reception", distance: 15, edgeType: "walk" },
  { from: "node-reception", to: "node-central-corridor", distance: 20, edgeType: "walk" },
  { from: "node-reception", to: "node-bathroom", distance: 25, edgeType: "walk" },
  { from: "node-central-corridor", to: "node-admissions", distance: 15, edgeType: "walk" },
  { from: "node-central-corridor", to: "node-[#1st-bedroom]", distance: 25, edgeType: "walk" },
  { from: "node-central-corridor", to: "node-dining-room", distance: 20, edgeType: "walk" },
  { from: "node-dining-room", to: "node-kitchen", distance: 15, edgeType: "walk" },
  { from: "node-central-corridor", to: "node-kitchen", distance: 35, edgeType: "walk" },
  { from: "node-kitchen", to: "node-porch", distance: 10, edgeType: "walk" },
  { from: "node-central-corridor", to: "node-library", distance: 20, edgeType: "walk" },
  { from: "node-central-corridor", to: "node-2nd-bedroom", distance: 30, edgeType: "walk" },
  { from: "node-2nd-bedroom", to: "node-bhagwan-room", distance: 15, edgeType: "walk" },
  { from: "node-central-corridor", to: "node-stairs-g", distance: 10, edgeType: "walk" },
  { from: "node-central-corridor", to: "node-elevator-g", distance: 10, edgeType: "walk" },

  // Floor Transitions (Stairs / Elevators)
  { from: "node-stairs-g", to: "node-stairs-1", distance: 20, edgeType: "stairs" },
  { from: "node-elevator-g", to: "node-elevator-1", distance: 15, edgeType: "elevator" },
  { from: "node-stairs-1", to: "node-stairs-2", distance: 20, edgeType: "stairs" },
  { from: "node-elevator-1", to: "node-elevator-2", distance: 15, edgeType: "elevator" },

  // First Floor Edges
  { from: "node-stairs-1", to: "node-faculty-cabins", distance: 30, edgeType: "walk" },
  { from: "node-[#faculty-cabins]", to: "node-faculty-room-201", distance: 10, edgeType: "walk" },
  { from: "node-elevator-1", to: "node-faculty-room-201", distance: 25, edgeType: "walk" },

  // Second Floor Edges
  { from: "node-stairs-2", to: "node-director-office", distance: 25, edgeType: "walk" },
];
