import type { Building, Destination, IndoorNode, NavigationEdge, Person, QRLocation } from "./wayfindr-types";

export const DEMO_BUILDING: Building = {
  id: "building-home",
  name: "Home Premises",
  floors: [
    { id: "G", name: "Ground Floor", level: "G" },
  ],
};

export const DEMO_NODES: IndoorNode[] = [
  { id: "node-main-gate", floorId: "G", x: 45, y: 88, name: "Main Gate", type: "entrance" },
  { id: "node-hall", floorId: "G", x: 45, y: 70, name: "Hall", type: "corridor" },
  { id: "node-1st-bedroom", floorId: "G", x: 20, y: 86, name: "1st Bedroom", type: "room" },
  { id: "node-dining-room", floorId: "G", x: 75, y: 52, name: "Dining Room", type: "room" },
  { id: "node-kitchen", floorId: "G", x: 75, y: 32, name: "Kitchen", type: "room" },
  { id: "node-bathroom", floorId: "G", x: 25, y: 50, name: "Bathroom", type: "restroom" },
  { id: "node-2nd-bedroom", floorId: "G", x: 25, y: 32, name: "2nd Bedroom", type: "room" },
  { id: "node-bhagwan-room", floorId: "G", x: 25, y: 12, name: "Bhagwan Room", type: "room" },
  { id: "node-porch", floorId: "G", x: 75, y: 12, name: "Porch", type: "room" },
];

export const DEMO_DESTINATIONS: Destination[] = [
  {
    id: "main-gate",
    name: "Main Gate",
    category: "Entrance",
    nodeId: "node-main-gate",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "MapPin",
    description: "Property entrance and starting checkpoint.",
    roomNumber: "Gate 1",
  },
  {
    id: "hall",
    name: "Hall",
    category: "Living",
    nodeId: "node-hall",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "Sofa",
    description: "Central living hall connecting all house rooms.",
    roomNumber: "Hall",
  },
  {
    id: "first-bedroom",
    name: "1st Bedroom",
    category: "Bedrooms",
    nodeId: "node-1st-bedroom",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "Bed",
    description: "Lower bedroom next to entrance.",
    roomNumber: "Bed 1",
  },
  {
    id: "dining-room",
    name: "Dining Room",
    category: "Dining",
    nodeId: "node-dining-room",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "Coffee",
    description: "Dining space connecting Hall and Kitchen.",
    roomNumber: "Dining Area",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    category: "Kitchen",
    nodeId: "node-kitchen",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "Utensils",
    description: "Food preparation area.",
    roomNumber: "Kitchen",
  },
  {
    id: "bathroom",
    name: "Bathroom",
    category: "Restroom",
    nodeId: "node-bathroom",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "Droplets",
    description: "Washroom and freshening area.",
    roomNumber: "Bathroom",
  },
  {
    id: "second-bedroom",
    name: "2nd Bedroom",
    category: "Bedrooms",
    nodeId: "node-2nd-bedroom",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "BedDouble",
    description: "Upper bedroom leading to Bhagwan Room.",
    roomNumber: "Bed 2",
  },
  {
    id: "bhagwan-room",
    name: "Bhagwan Room",
    category: "Prayer",
    nodeId: "node-bhagwan-room",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "Flame",
    description: "Sanctuary prayer and meditation room.",
    roomNumber: "Prayer Room",
  },
  {
    id: "porch",
    name: "Porch",
    category: "Outdoor",
    nodeId: "node-porch",
    floorId: "G",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    icon: "Sun",
    description: "Outdoor porch area adjacent to kitchen.",
    roomNumber: "Porch",
  },
];

export const DEMO_PEOPLE: Person[] = [
  {
    id: "person-tarun",
    name: "Tarun Kumar",
    title: "Property Owner / Resident",
    department: "Home",
    destinationId: "first-bedroom",
    nodeId: "node-1st-bedroom",
    roomNumber: "1st Bedroom",
    floorName: "Ground Floor",
    buildingName: "Home Premises",
  },
  {
    id: "person-tanya",
    name: "Tanya Sharma",
    title: "Resident",
    department: "Home",
    destinationId: "dining-room",
    nodeId: "node-dining-room",
    roomNumber: "Dining Room",
    floorName: "Ground Floor",
    buildingName: "Home Premises",
  },
  {
    id: "person-rahul",
    name: "Rahul Verma",
    title: "Visitor / Guest",
    department: "Guest",
    destinationId: "hall",
    nodeId: "node-hall",
    roomNumber: "Hall",
    floorName: "Ground Floor",
    buildingName: "Home Premises",
  },
  {
    id: "person-ananya",
    name: "Dr. Ananya Roy",
    title: "Resident Doctor",
    department: "Home",
    destinationId: "bhagwan-room",
    nodeId: "node-bhagwan-room",
    roomNumber: "Bhagwan Room",
    floorName: "Ground Floor",
    buildingName: "Home Premises",
  },
  {
    id: "person-priya",
    name: "Priya Patel",
    title: "Resident",
    department: "Home",
    destinationId: "second-bedroom",
    nodeId: "node-2nd-bedroom",
    roomNumber: "2nd Bedroom",
    floorName: "Ground Floor",
    buildingName: "Home Premises",
  },
  {
    id: "person-amit",
    name: "Amit Shah",
    title: "Kitchen In-charge",
    department: "Home",
    destinationId: "kitchen",
    nodeId: "node-kitchen",
    roomNumber: "Kitchen",
    floorName: "Ground Floor",
    buildingName: "Home Premises",
  },
];

export const DEMO_QR_LOCATIONS: Record<string, QRLocation> = {
  "main-gate": {
    qrId: "main-gate",
    nodeId: "node-main-gate",
    locationName: "Main Gate",
    buildingName: "Home Premises",
    floorName: "Ground Floor",
    floorId: "G",
  },
};

export const DEMO_EDGES: NavigationEdge[] = [
  { from: "node-main-gate", to: "node-hall", distance: 7.0, edgeType: "walk" },
  { from: "node-hall", to: "node-1st-bedroom", distance: 0.5, edgeType: "walk" },
  { from: "node-hall", to: "node-dining-room", distance: 0.5, edgeType: "walk" },
  { from: "node-hall", to: "node-kitchen", distance: 4.0, edgeType: "walk" },
  { from: "node-dining-room", to: "node-kitchen", distance: 1.5, edgeType: "walk" },
  { from: "node-hall", to: "node-bathroom", distance: 2.0, edgeType: "walk" },
  { from: "node-hall", to: "node-2nd-bedroom", distance: 3.0, edgeType: "walk" },
  { from: "node-2nd-bedroom", to: "node-bhagwan-room", distance: 3.0, edgeType: "walk" },
  { from: "node-kitchen", to: "node-porch", distance: 0.5, edgeType: "walk" },
];
