/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as QrIdRouteImport } from './routes/qr.$id'
import { Route as NavigateIdRouteImport } from './routes/navigate.$id'
import { Route as LocationIdRouteImport } from './routes/location.$id'
import { Route as AdminQrRouteImport } from './routes/admin.qr'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminIdEditRouteImport } from './routes/admin.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const QrIdRoute = QrIdRouteImport.update({
  id: '/qr/$id',
  path: '/qr/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateIdRoute = NavigateIdRouteImport.update({
  id: '/navigate/$id',
  path: '/navigate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIdRoute = LocationIdRouteImport.update({
  id: '/location/$id',
  path: '/location/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQrRoute = AdminQrRouteImport.update({
  id: '/admin/qr',
  path: '/admin/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdEditRoute = AdminIdEditRouteImport.update({
  id: '/admin/$id/edit',
  path: '/admin/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/qr': typeof AdminQrRoute
  '/location/$id': typeof LocationIdRoute
  '/navigate/$id': typeof NavigateIdRoute
  '/qr/$id': typeof QrIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$id/edit': typeof AdminIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/qr': typeof AdminQrRoute
  '/location/$id': typeof LocationIdRoute
  '/navigate/$id': typeof NavigateIdRoute
  '/qr/$id': typeof QrIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/$id/edit': typeof AdminIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/qr': typeof AdminQrRoute
  '/location/$id': typeof LocationIdRoute
  '/navigate/$id': typeof NavigateIdRoute
  '/qr/$id': typeof QrIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/$id/edit': typeof AdminIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/new'
    | '/admin/qr'
    | '/location/$id'
    | '/navigate/$id'
    | '/qr/$id'
    | '/admin/'
    | '/admin/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/new'
    | '/admin/qr'
    | '/location/$id'
    | '/navigate/$id'
    | '/qr/$id'
    | '/admin'
    | '/admin/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/admin/new'
    | '/admin/qr'
    | '/location/$id'
    | '/navigate/$id'
    | '/qr/$id'
    | '/admin/'
    | '/admin/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminQrRoute: typeof AdminQrRoute
  LocationIdRoute: typeof LocationIdRoute
  NavigateIdRoute: typeof NavigateIdRoute
  QrIdRoute: typeof QrIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminIdEditRoute: typeof AdminIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr/$id': {
      id: '/qr/$id'
      path: '/qr/$id'
      fullPath: '/qr/$id'
      preLoaderRoute: typeof QrIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate/$id': {
      id: '/navigate/$id'
      path: '/navigate/$id'
      fullPath: '/navigate/$id'
      preLoaderRoute: typeof NavigateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$id': {
      id: '/location/$id'
      path: '/location/$id'
      fullPath: '/location/$id'
      preLoaderRoute: typeof LocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/qr': {
      id: '/admin/qr'
      path: '/admin/qr'
      fullPath: '/admin/qr'
      preLoaderRoute: typeof AdminQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id/edit': {
      id: '/admin/$id/edit'
      path: '/admin/$id/edit'
      fullPath: '/admin/$id/edit'
      preLoaderRoute: typeof AdminIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminNewRoute: AdminNewRoute,
  AdminQrRoute: AdminQrRoute,
  LocationIdRoute: LocationIdRoute,
  NavigateIdRoute: NavigateIdRoute,
  QrIdRoute: QrIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminIdEditRoute: AdminIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
